"""The CountSketch map is compact on the device and historical everywhere else.

The device-resident tables cost one int64 bucket and one float64 sign per
parameter -- 16 bytes -- which at 134M parameters is 2 GiB of a single card, and
four independent maps would be 8 GiB. Narrowing them to int32 buckets and int8
signs costs 5 bytes per parameter instead.

That saving is only admissible if it changes nothing measurable. Two properties
carry the whole argument, and both are pinned here against a frozen reference
generated by the implementation that predates the change:

* the **map itself** is drawn exactly as before -- same generator per tensor,
  same seed formula, buckets before signs, historical draw dtypes -- and only
  then narrowed, so no RNG stream moved;
* the **projection** is bit-identical, because int32 indices address the same
  buckets and int8 signs promote to exactly +/-1.0.

The reference lives in ``tests/assets/countsketch_golden_map_v1.npz`` and must
never be regenerated from the code it checks. See the header of
``tests/assets/make_countsketch_golden.py``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import torch

from llm_behavior_lab.evaluation.position_gradients import (
    DEFAULT_SKETCH_DIMENSION,
    _SKETCH_BUCKET_DEVICE_DTYPE,
    _SKETCH_MAP_DEVICE_BYTES_PER_PARAMETER,
    _SKETCH_SIGN_DEVICE_DTYPE,
    _GradientSketcher,
    production_sketch_map,
    production_sketch_tables,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
GOLDEN = REPO_ROOT / "tests" / "assets" / "countsketch_golden_map_v1.npz"


@pytest.fixture(scope="module")
def golden():
    """The frozen pre-change reference: map values and the float64 projection."""

    # allow_pickle=False stated rather than inherited: the fixture is checked-in
    # binary test data and must never be able to execute anything on load.
    with np.load(GOLDEN, allow_pickle=False) as archive:
        return {key: archive[key].copy() for key in archive.files}


def _sizes(golden) -> tuple[int, ...]:
    return tuple(int(value) for value in golden["tensor_sizes"])


def _gradients(golden) -> list[torch.Tensor]:
    """Rebuilt from the same RNG-free formula the fixture generator used."""

    return [
        torch.arange(size, dtype=torch.float64) * 0.5 - 1.25
        for size in _sizes(golden)
    ]


def _sketcher(golden) -> _GradientSketcher:
    return _GradientSketcher(
        [torch.zeros(size) for size in _sizes(golden)],
        dimension=int(golden["dimension"]),
        seed=int(golden["seed"]),
    )


# -- the public contracts, unchanged ------------------------------------------


def test_production_sketch_tables_keeps_its_historical_dtypes(golden) -> None:
    """The public helper is the map's canonical form and did not move.

    The fidelity analysis and every persisted ``sketch_map`` read these dtypes,
    so narrowing the device tables must not narrow this.
    """

    tables = production_sketch_tables(_sizes(golden), int(golden["dimension"]), int(golden["seed"]))

    assert all(buckets.dtype is torch.int64 for buckets, _ in tables)
    assert all(signs.dtype is torch.float64 for _, signs in tables)
    assert np.array_equal(np.concatenate([b.numpy() for b, _ in tables]), golden["buckets"])
    assert np.array_equal(np.concatenate([s.numpy() for _, s in tables]), golden["signs"])


def test_production_sketch_map_is_unchanged(golden) -> None:
    buckets, signs = production_sketch_map(
        _sizes(golden), int(golden["dimension"]), int(golden["seed"])
    )

    assert buckets.dtype == np.int64
    assert signs.dtype == np.float64
    assert np.array_equal(buckets, golden["buckets"])
    assert np.array_equal(signs, golden["signs"])


def test_the_exported_map_is_widened_back_to_the_historical_dtypes(golden) -> None:
    """``numpy_map`` is public: compact storage must not leak into it."""

    buckets, signs = _sketcher(golden).numpy_map()

    assert buckets.dtype == np.int64
    assert signs.dtype == np.float64
    assert np.array_equal(buckets, golden["buckets"])
    assert np.array_equal(signs, golden["signs"])


# -- the device tables, compact -----------------------------------------------


def test_the_device_tables_are_int32_and_int8(golden) -> None:
    """5 bytes per parameter per map instead of 16."""

    sketcher = _sketcher(golden)

    assert all(buckets.dtype is torch.int32 for buckets in sketcher.buckets)
    assert all(signs.dtype is torch.int8 for signs in sketcher.signs)
    assert sum(b.element_size() for b in sketcher.buckets[:1]) == 4
    assert sum(s.element_size() for s in sketcher.signs[:1]) == 1


def test_int8_signs_reconstruct_exactly_plus_and_minus_one(golden) -> None:
    """The promotion at the multiply must be exact, not merely close."""

    sketcher = _sketcher(golden)
    for signs in sketcher.signs:
        values = set(signs.tolist())
        assert values <= {-1, 1}
        promoted = signs.to(torch.float64)
        assert torch.equal(promoted, torch.sign(promoted))
        assert set(promoted.tolist()) <= {-1.0, 1.0}


def test_int32_indices_are_accepted_by_index_add(golden) -> None:
    """Pinned rather than assumed: index_add_ takes int32 or int64, not int16."""

    sketch = torch.zeros(4, dtype=torch.float64)
    index = torch.tensor([0, 2, 2, 3], dtype=torch.int32)

    sketch.index_add_(0, index, torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.float64))

    assert sketch.tolist() == [1.0, 0.0, 5.0, 4.0]


# -- identity against the frozen reference ------------------------------------


def test_the_map_values_equal_the_frozen_reference(golden) -> None:
    """Same buckets and signs, entry for entry, in parameter order."""

    sketcher = _sketcher(golden)
    buckets = np.concatenate([b.cpu().to(torch.int64).numpy() for b in sketcher.buckets])
    signs = np.concatenate([s.cpu().to(torch.float64).numpy() for s in sketcher.signs])

    assert np.array_equal(buckets, golden["buckets"])
    assert np.array_equal(signs, golden["signs"])
    assert buckets.shape == (sum(_sizes(golden)),)


def test_the_cpu_projection_is_bit_identical_to_the_frozen_reference(golden) -> None:
    """``torch.equal``, not ``allclose``: no tolerance is being spent here."""

    sketch = _sketcher(golden).project(_gradients(golden))

    assert sketch.dtype is torch.float64
    assert torch.equal(sketch, torch.from_numpy(golden["sketch"]))


def test_the_projection_still_accumulates_in_float64(golden) -> None:
    """Narrowing the tables must not narrow the accumulator."""

    assert _sketcher(golden).project(_gradients(golden)).dtype is torch.float64


# -- nothing observable moved -------------------------------------------------


def test_the_sketcher_reports_the_same_public_state(golden) -> None:
    sketcher = _sketcher(golden)

    assert sketcher.dimension == int(golden["dimension"])
    assert sketcher.seed == int(golden["seed"])
    assert sketcher.tensor_sizes == list(_sizes(golden))


def test_a_default_width_sketcher_still_produces_the_declared_shape() -> None:
    """One map, K columns: no map-count or shape change is visible anywhere."""

    sketcher = _GradientSketcher([torch.zeros(6), torch.zeros(4)])

    sketch = sketcher.project([torch.ones(6, dtype=torch.float64), torch.ones(4, dtype=torch.float64)])

    assert sketcher.dimension == DEFAULT_SKETCH_DIMENSION
    assert sketch.shape == (DEFAULT_SKETCH_DIMENSION,)
    buckets, _ = sketcher.numpy_map()
    assert buckets.shape == (10,)


# -- fixture provenance -------------------------------------------------------


def test_the_fixture_declares_the_source_it_was_frozen_from(golden) -> None:
    """A reference is only worth having if it names what it froze."""

    assert int(golden["fixture_version"]) == 1
    assert str(golden["source_commit"]) == "4df44246d6dff573e12ec40c8c62ce0c079bc008"
    assert str(golden["source_path"]) == "src/llm_behavior_lab/evaluation/position_gradients.py"
    assert len(str(golden["source_sha256"])) == 64


def test_the_fixture_provenance_matches_the_committed_blob(golden) -> None:
    """The recorded hash must be that commit's actual blob, not a claim.

    This is what makes the reference independent: it was produced by the
    implementation as committed, which is provable here from git rather than
    taken on trust from a docstring.
    """

    import hashlib
    import subprocess

    blob = subprocess.run(
        [
            "git", "-C", str(REPO_ROOT), "cat-file", "blob",
            f"{str(golden['source_commit'])}:{str(golden['source_path'])}",
        ],
        check=True,
        capture_output=True,
    ).stdout

    assert hashlib.sha256(blob).hexdigest() == str(golden["source_sha256"])


# -- byte accounting stays synchronized ---------------------------------------


def test_the_reported_bytes_per_parameter_match_the_real_device_dtypes(golden) -> None:
    """The benchmark prints this number; it must be derived, never written down.

    A hard-coded copy of it in the benchmark already went stale once, the moment
    the dtypes changed. This fails if the constant, the declared dtypes and the
    tensors actually allocated ever disagree.
    """

    sketcher = _sketcher(golden)
    measured = (
        sketcher.buckets[0].element_size() + sketcher.signs[0].element_size()
    )

    assert measured == _SKETCH_MAP_DEVICE_BYTES_PER_PARAMETER
    assert sketcher.buckets[0].dtype is _SKETCH_BUCKET_DEVICE_DTYPE
    assert sketcher.signs[0].dtype is _SKETCH_SIGN_DEVICE_DTYPE


def test_the_benchmark_reports_the_implementation_owned_constant() -> None:
    """One source of truth, imported rather than restated."""

    import importlib.util
    import sys

    path = REPO_ROOT / "scripts" / "benchmark_position_gradients.py"
    spec = importlib.util.spec_from_file_location("benchmark_bytes_check", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

    assert module._SKETCH_MAP_DEVICE_BYTES_PER_PARAMETER == _SKETCH_MAP_DEVICE_BYTES_PER_PARAMETER


# -- parameters must be reusable ----------------------------------------------


def test_a_generator_of_parameters_still_produces_complete_tables() -> None:
    """``parameters`` is consumed three times; a one-shot iterator would empty it.

    Before this was materialized, passing a generator produced correct
    ``tensor_sizes`` and then **empty** bucket and sign lists -- silently,
    because zip over an empty list yields nothing and ``project`` would return an
    all-zero sketch with no error at all.
    """

    sizes = (7, 5, 11, 3)
    from_generator = _GradientSketcher(
        (torch.zeros(size) for size in sizes), dimension=8, seed=20240917
    )
    from_list = _GradientSketcher(
        [torch.zeros(size) for size in sizes], dimension=8, seed=20240917
    )

    assert from_generator.tensor_sizes == list(sizes)
    assert len(from_generator.buckets) == len(sizes)
    assert len(from_generator.signs) == len(sizes)

    grads = [torch.arange(size, dtype=torch.float64) * 0.5 - 1.25 for size in sizes]
    assert torch.equal(from_generator.project(grads), from_list.project(grads))
